#!/bin/bash

if [ -z "$1" -o \! -d "$1" ]
then
    echo "Usage: $0 <year> [year...]"
else
    cd /srv/img
    while (( $# > 0 ))
    do
        rclone copy --s3-storage-class=STANDARD $1 "scaleway:rolfrander-img/$1/" 
        echo "rclone $1 done, return code $?"
        shift
    done
fi

