#!/bin/bash

if (( $# == 0 ))
then
    echo "Usage: $0 <year> [year...]"
    exit 1
fi

cd /srv/img
error=0

for y in $*
do
    if [ \! -d "$y" ]
    then
        echo "$y is not a valid year, does not exist in $PWD"
        error=2
    fi
done

if (( $error > 0 ))
then exit $error
fi

while (( $# > 0 ))
do
    rclone copy --s3-storage-class=STANDARD $1 "scaleway:rolfrander-img/$1/" 
    echo "rclone $1 done, return code $?"
    shift
done

